### PR TITLE
add filter to branch dropdown menu

### PR DESCRIPTION
**Pull request by tkgdsg**
If repo has so many branches, it is hard to find expected one.
This patch enables to apply filter to branch list.
Filter algorithm is same as gitbucket's, it is intermediate match and case insensitive.

### CODE REVIEW

**Comment by mrkm4ntr** [comment]
Could you resolve conflict and change code not to use jQuery?
React state should have filter value and branches should be filtered in render method. Events should be bound input element by onKeyUp and onClick.

**Comment by tkgdsg** [comment]
Thank you for your review.

Do you mean, "do not catch event by addEventListener" ?

**Comment by mrkm4ntr** [comment]
> Do you mean, "do not catch event by addEventListener" ?

Yes!
You need not to check which element fired the event if you catch event in [react way].(https://facebook.github.io/react/docs/handling-events.html)

**Comment by tkgdsg** [comment]
Sorry for late creating patch.
I use FormControl and react event mechanism to implement same action.
But I cannot find a way not use jquery at all.
If you have a suggestion in order not to use jquery, please give me a comment.

**Comment by mrkm4ntr** [comment]
Hi, thank you for creating a patch.
You do not need to use jquery if you do like following.

```diff
diff --git a/.eslintrc b/.eslintrc
index 6d4b42f..6ddd117 100644
--- a/.eslintrc
+++ b/.eslintrc
@@ -14,8 +14,5 @@
   "rules": {
     "react/jsx-uses-react": "error",
     "react/jsx-uses-vars": "error"
-  },
-  "env": {
-    "jquery": true
   }
 }
diff --git a/scripts/components/App.js b/scripts/components/App.js
index 2596884..2c34742 100755
--- a/scripts/components/App.js
+++ b/scripts/components/App.js
@@ -19,6 +19,7 @@ export default class App extends React.Component {
     super(props);
     this.selectBranch = this.selectBranch.bind(this);
     this.selectCount = this.selectCount.bind(this);
+    this.doFilter = this.doFilter.bind(this);
     this.state = {
       maxLane: 0,
       commits: [],
@@ -64,7 +65,10 @@ export default class App extends React.Component {
     return window.fetch(`./network/commits?${query}`, { credentials: 'include' }).then(
       r => r.json()
     ).then(data => {
-      const newState = Object.assign({ count: params.count, isFetching: false }, data);
+      const newState = Object.assign({
+        count: params.count,
+        isFetching: false,
+      }, data, { branches: data.branches.map(branch => ({ branch, visible: true })) });
       if (data.all) {
         newState.currentBranch = App.allBranchName;
       }
@@ -83,21 +87,12 @@ export default class App extends React.Component {
   }
 
   doFilter(e) {
-    const branchFilter = $(e.target);
-    const inputVal = branchFilter.val();
-    $.each(
-      branchFilter.parent().parent().parent()
-      .find('a'),
-        (index, elem) => {
-          if (!inputVal ||
-            !elem.text.trim() ||
-            elem.text.trim().toLowerCase().indexOf(inputVal.toLowerCase()) >= 0) {
-            $(elem).parent().show();
-          } else {
-            $(elem).parent().hide();
-          }
-        }
-    );
+    this.setState(Object.assign(this.state, {
+      branches: this.state.branches.map(({ branch }) => ({
+        branch,
+        visible: branch.startsWith(e.target.value.trim()),
+      })),
+    }));
   }
 
   render() {
@@ -125,7 +120,7 @@ export default class App extends React.Component {
             />
           </MenuItem>
           <MenuItem divider />
-          {this.state.branches.map(branch =>
+          {this.state.branches.filter(({ visible }) => visible).map(({ branch }) =>
```

In this way, you can take advantage of React's update with Virtual DOM and make the rendering smoother.

**Comment by tkgdsg** [comment]
Than you for your comment and suggestion.
I updated my code "not using jquery expression" using your suggestion.
And added filter clear function.

**Comment by mrkm4ntr** [comment]
Sorry for the late response. Thank you for your contribution!

**Pull request merged**
